const actionTypes = {
  STALEMATE: "STALEMATE",
  CAN_CASTLE: "CAN_CASTLE",
  NEW_MOVE: "NEW_MOVE",
  GENERATE_CANDIDATE_MOVES: "GENERATE_CANDIDATE_MOVES",
  CLEAR_CANDIDATE_MOVES: "CLEAR_CANDIDATE_MOVES",
  PROMOTION_OPEN: "PROMOTION_OPEN",
  NEW_GAME: "NEW_GAME",
  PROMOTION_CLOSE: "PROMOTION_CLOSE",
  INSUFFICIENT_MATERIAL: "INSUFFICIENT_MATERIAL",
};
export default actionTypes;
